name: Clean up issues & PRs

on:
  schedule:
  - cron: '31 14 * * *'
  workflow_dispatch:

jobs:
  check_stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:    
    - name: Mark stale issues and PRs, and close inactive PRs
      uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }} # where was this set? 
        days-before-stale: 1 # for testing
        # days-before-issue-stale: 365 # or mark it stale after a next release?
        days-before-issue-close: -1 
        days-before-pr-stale: 3
        days-before-pr-close: 21
        
        stale-issue-message: 'This PR has become stale. It will be automatically closed if it remains stale for too long.'
        stale-pr-message: 'This PR has become stale. It will be automatically closed if it remains stale for too long.'
        stale-issue-label: 'stale.check-relevancy'
        stale-pr-label: 'stale.pr'
        close-pr-message: 'This PR has been automatically closed because of inactivity. Feel free to reopen the PR if you wish to continue.'
        close-pr-label: 'closed-automatically'
        exempt-issue-labels: 'c.Epic,help wanted,good first issue,good second issue'
        exempt-pr-labels: 'S.ToMerge'
        
        debug-only: false
        
    - name: Run a one-line script
      run: echo Hello, world!

# Good to have workflows   
    #   auto add a comment on PRs that need reviews, if the checks are passing but no reviews have been made in x days since PR was ready for review
    #   comment on stale PRs with S.ToMerge (stale can be used, run this an hour later to not overrun github api limits) 
      
    
     
    
